### ISSUE TITLE
Create the dumb end-to-end proof of concept

### ISSUE THREAD

**Issue by jorgenbuilder** [metascore/metascore#12]
The point: derisk all of the scary technical parts so that we can all be confident that this thing is going to work. Enables us to promote more aggressively, etc.

- [ ] Game canisters can register with metascore
- [ ] Metascore can query game canisters for all scores
- [ ] Game canisters can't trip us up with weird responses
- [ ] Polling mechanism will work at scale
- [ ] Etc.

**Comment by di-wu** [comment]
Here are my 2¢ (a.k.a. thoughts) on this matter.
It might not be very organised, or in any specific order.

Feel free to comment if you have any questions.

---

First I imagine one central metascore canister that is used in the frontend to display information.
This canister is responsible for orchestrating this whole this.

What does this mean, 'orchestrating'? I will omit any countermeasures that has to do with sybil-attacks for the time being.

1. A canister can register **itself** as a game canister by calling an endpoint on the metascore canister. This would contain information such as the name, creators, etc. This would also prevent the registration of too many canisters since the canister itself need to exist first.
2. The canister, that just called this endpoint, also need to implement some kind of `scoring` endpoint so the metascore canister can call this on a certain interval. This information then is stored (\*).

---

Additional/Other options:

- (**\***) Let games host their own score canisters, the metascore canister just redirects the traffic.
- We create a new canister to store the scores of (verified/big) games to not overload the metascore canister.
